CREATE TABLE IF NOT EXISTS admins (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  nome VARCHAR(255),
  cognome VARCHAR(255),
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  ruolo VARCHAR(64) DEFAULT 'ROLE_ADMIN'
);
